FROM wordpress:latest
LABEL authors="gearbox.works"

RUN apt-get update && \
    apt-get install nano && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    cd /usr/local/etc/php && \
    cp php.ini-development php.ini && \
    printf "\n\
xdebug.mode=debug\n\
xdebug.client_port=9003\n\
xdebug.start_with_request=yes\n\
xdebug.log=/var/log/xdebug.log\n\
xdebug.idekey=PHPSTORM\n\
xdebug.discover_client_host=true\n\
" >> conf.d/docker-php-ext-xdebug.ini

