version: '3.8'

networks:
  shared_network:
    # This must be created as a bridge network first
    # Set to `172.20.0.0/16` and  `172.20.0.11`.
    name: shared
    external: true

services:
  traefik.local:
    # The Gearbox Works extension of v2 Traefik Docker image
    # which just adds /etc/traefik/traefik.yaml
    image: gbw-traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    networks:
    - shared_network
    extra_hosts:
    - "wordpress.local:192.168.1.110"
    - "step-ca.local:192.168.1.110"
    - "traefik.local:192.168.1.110"
    restart: unless-stopped
    environment:
      LEGO_CA_CERTIFICATES: "/etc/step/certs/root_ca.crt"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
    - "traefik.http.routers.traefik.service=traefik"
    - "traefik.http.routers.traefik.entrypoints=websecure,web"
    - "traefik.http.routers.traefik.tls.certresolver=default"
    - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    - "traefik.http.routers.traefik-api.rule=PathPrefix(`/api`)"
    - "traefik.http.routers.traefik-api.service=api@internal"
    - "traefik.http.routers.traefik.entrypoints=websecure"

    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # So we can edit the traefik.yaml on the Portainer VM
      - /etc/traefik:/etc/traefik
      # So Traefik can access Step CA's root cert (read-only)
      - /etc/step:/etc/step:ro
      # Allow traefik logs to be accessible on Portainer VM
      - /var/log/traefik:/var/log/traefik
      # Use the host's SLL certificate store
      - /etc/ssl/certs:/etc/ssl/certs

