version: '3.8'

networks:
  shared_network:
    name: shared
    external: true

services:
  php:
    image: xdebug-wordpress:latest
    networks:
    - shared_network
    ports:
    - 8888:80
    - 9003:9003
    restart: unless-stopped
    environment:
      LEGO_CA_CERTIFICATES: "/etc/step/certs/root_ca.crt"
      LEGO_CA_SERVER_NAME: "step-ca.local"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`)"
    - "traefik.http.routers.wordpress.service=wordpress@docker"
    - "traefik.http.routers.wordpress.entrypoints=websecure,web"
    - "traefik.http.routers.wordpress.tls.certresolver=default"
    - "traefik.http.routers.wordpress.tls.domains[0].main=wordpress.local"
    - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    # Port 80 above matches internal port, i.e. <external>:<internal> e.g. 8888:80

#    - "traefik.http.routers.dww_store.rule=Host(`dww.local`)"
#    - "traefik.http.routers.dww_store.service=wordpress@docker"
#    - "traefik.http.routers.dww_store.entrypoints=websecure,web"
#    - "traefik.http.services.dww_store.loadbalancer.server.port=80"
#
#    # This is so I can test replacing wordpress.local with a longer name in the MySQL db
#    - "traefik.http.routers.wordpress.rule=Host(`thecultofwordpress.local`)"
#    - "traefik.http.routers.davisworkwear.service=wordpress@docker"
#    - "traefik.http.routers.davisworkwear.entrypoints=websecure,web"
#    - "traefik.http.services.davisworkwear.loadbalancer.server.port=80"

    volumes:
    # Store the WordPress source code remotely on user's computer
    # Requires configuration
    # On macOS: step certificate install ~/Downloads/roots.pem
    - wordpress-root:/var/www/html
    # So Traefik can access Step CA's root cert (read-only)
    - /etc/step:/etc/step:ro
    # Use the host's SLL certificate store
    - /etc/ssl/certs:/etc/ssl/certs

  db:
    image: wp-mysql:latest
    networks:
    - shared_network
    ports:
    - 33306:3306
    volumes:
    - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data:
  wordpress-root:
    external: true

